### ISSUE TITLE
Wildly wrong numbers

### ISSUE THREAD

**Issue by MikeyMoMo** [jpb10/SolarCalculator#1]
Could you please run your example code SunriseSunset.ino with the following numbers and see why it is giving such odd numbers?

```
// Date
int year = 2022;
int month = 1;
int day = 15;

// Location
double latitude  = 18.19;
double longitude = 120.55;
int time_zone    = -8;
```

With those figures, I get: 

```
Date: 2022-1-15
Latitude: 18.190 Longitude: 120.550
UTC offset: -8
--
Sunrise: 0-9:0-28
Transit: 0-3:0-53
Sunset:  01:42
Civil dawn: 0-9:0-51
Civil dusk: 02:05
```

ESP32.  Arduino IDE. Nothing changed in the library or example code except the lat/long and date values at the top.

**Comment by jpb10** [comment]
At this location (Philippines), the UTC offset is actually +8. 

By convention, longitude is positive west of Greenwich, negative to the east. 

```
Date: 2022-1-15
Latitude: 18.190 Longitude: 120.550
UTC offset: 8
--
Sunrise: 06:32
Transit: 12:07
Sunset:  17:42
Civil dawn: 06:09
Civil dusk: 18:05
```
