### ISSUE TITLE
Sunset (and probably sunrise) calculations for next day

### ISSUE THREAD

**Issue by Macintosh-Fan** [jpb10/SolarCalculator#10]
In this program, the UTC day is Nov 11, 2022, but my local date is Nov 10, 2022. When the program calculates the sunset time using the unix epoch (using my `utc_now` variable), it calculates the sunset at my location for the next day, not for the current date.

```cpp
unsigned long utc_now = 1668127050;
calcSunriseSunset(utc_now, LATITUDE, LONGITUDE, transit, sunrise, sunset);

// Printed as seconds after midnight.
std::cout << utc_now % 86400 << '\n';
std::cout << sunset * 3600 - 86400 << '\n';

// My correction
if (sunset > 24) {
    utc_now -= 86400;
    calcSunriseSunset(utc_now, LATITUDE, LONGITUDE, transit, sunrise, sunset);

    // Printed as seconds after midnight.
    std::cout << utc_now % 86400 << '\n';
    std::cout << sunset * 3600 - 86400 << '\n';
}
```

**Comment by Macintosh-Fan** [comment]
I forget the details, but when I did another location for testing a glitch with the sunrise time, I got a negative sunrise time.

**Comment by jpb10** [comment]
For example, in San Francisco (37.77, -122.42) on Nov 10, 2022, sunset is at 17:02 PST, or 01:02 GMT (Nov 11).

Did you want the sunrise and sunset times restrained to the current UTC day?

**Comment by Macintosh-Fan** [comment]
> For example, in San Francisco (37.77, -122.42) on Nov 10, 2022, sunset is at 17:02 PST, or 01:02 GMT (Nov 11).
> 
> 
> 
> Did you want the sunrise and sunset times restrained to the current UTC day?

Yes. The problem is that it will calculate for Nov 11 for San Francisco, not Nov 10 in your example.

**Comment by jpb10** [comment]
In San Francisco (37.77, -122.42) on timestamp `1668127050` (Nov 11, GMT), the output times are:

14:46 (Nov 11, GMT)
19:54 (Nov 11, GMT)
01:01 (Nov 12, GMT)

By default, the algorithm computes event times intended to be converted to local time, i.e. in chronological order. 

06:46 (Nov 11, PST)
11:54 (Nov 11, PST)
17:01 (Nov 11, PST)

If you want to restrain the output times to the current UTC day, you have to change lines [240](https://github.com/jpb10/SolarCalculator/blob/main/src/SolarCalculator.cpp#L240)~[242](https://github.com/jpb10/SolarCalculator/blob/main/src/SolarCalculator.cpp#L242) to:

```
m[0] = wrapTo360(ra - longitude - GMST + jd.m * 360) / 360;
m[1] = wrapTo360(m[0] * 360 - H0) / 360;
m[2] = wrapTo360(m[0] * 360 + H0) / 360;
```

which gives:

14:46 (Nov 11, GMT)
19:54 (Nov 11, GMT)
01:02 (Nov 11, GMT)

**Comment by Macintosh-Fan** [comment]
That works!
