### ISSUE TITLE
Incorrect rise/set times for Fiji, Nadi and other locations.

### ISSUE THREAD

**Issue by marius-sucan** [jpb10/SolarCalculator#6]
Hello!

I have found a systematic issue:

double lat = -17.803;  // fiji, nadi
double lon = 177.416;// fiji, nadi
int y = 2022;
int m = 9;
int d = 27;
calcSunriseSunset(y, m, d, lat, lon, transit, sunrise, sunset, SUNRISESET_STD_ALTITUDE, 2);

The function returns sunrise = -6.062. This is correct. However , if we set m = 10, the next month, the sunrise value jumps to 17.560.  If I feed it UTC time, the date differs when the «jump» to a sunrise at 17h occurs.  I tried the function with different iteration levels: 1, 5, 10... Nothing helped.

I found a similar thing happens for other locations in Fiji, and in Funafuti [Tuvalu], Apia [Samoa], Nuku'alofa [Tonga] and others. But, at different dates.

Please let me know if you can confirm the bug. Thank you . 

Best regards, Marius.

**Comment by jpb10** [comment]
I'm looking into it. Thanks.

**Comment by jpb10** [comment]
I removed the 0-24 hour constraint on the transit time, which could cause a one day jump in zones UTC±12 and beyond.

Let me know if you have further issues. Thanks.

**Comment by marius-sucan** [comment]
Hello!

Thank you for the fix.

Based on my tests... these locations are fixed now:
Tuvalu|Funafuti|-8.524|179.194|12.0
Fiji|Labasa|-16.433|179.365|12.0
Fiji|Lautoka|-17.617|177.450|12.0
Fiji|Nadi|-17.803|177.416|12.0
Fiji|Suva|-18.142|178.441|12.0

But for the following locations, I get results for tomorrow:
Samoa|Apia|-13.833|-171.767|13.0
Tonga|Nuku‘alofa|-21.139|-175.202|13.0
(Wallis and Futuna) Mata-Utu|-13.282|-176.175|12.0

Is this expected behaviour?

Best regards, Marius.

**Comment by jpb10** [comment]
Yes, I think those are the expected results (same as NOAA).

I suppose there are historical reasons behind why those places have positive UTC offsets, instead of negative.

**Comment by marius-sucan** [comment]
Thank you. 

You can close the issue.

Best regards, Marius.
